- hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - dellemc.enterprise_sonic

  tasks: 
    - name: VRF Mgmt
      vars:
        ansible_connection: network_cli
      sonic_config:
        lines:
          - ip vrf mgmt
      register: result
    - pause:
        seconds: 30

    - name: Push Configurations For Custom CLIs. pre
      vars:
        ansible_connection: network_cli
      sonic_config:
        src: fdc_clis_pre.j2
      register: result

    - name: Delete all system related configs in device configuration
      dellemc.enterprise_sonic.sonic_system:
        config:
        state: deleted

    - name: Configure Port Breakouts
      sonic_port_breakout:
        config: '{{sonic_port_breakout}}'
      when: sonic_port_breakout is defined and sonic_port_breakout
    
    - name: Deletes all the VLANs on the switch
      dellemc.enterprise_sonic.sonic_vlans:
        config:
        state: deleted
    
    - name: Deletes all LAGs and LAG attributes of all interfaces
      dellemc.enterprise_sonic.sonic_lag_interfaces:
        config:
        state: deleted
    
    - name: Configures interfaces
      dellemc.enterprise_sonic.sonic_interfaces:
        config:
        state: deleted
    
    - name: Configures switch port of interfaces
      dellemc.enterprise_sonic.sonic_l2_interfaces:
        config:
        state: deleted
    
    - name: Create VRF
      sonic_vrfs:
        config: '{{sonic_vrf_interfaces}}'
      when: sonic_vrf_interfaces is defined and sonic_vrf_interfaces
    
    - name: delete all l3 interface
      dellemc.enterprise_sonic.sonic_l3_interfaces:
        config:
        state: deleted
    
    - name: Delete all device configuration
      dellemc.enterprise_sonic.sonic_mclag:
        config:
        state: deleted
    
    - name: Deletes all the bgp global configurations
      dellemc.enterprise_sonic.sonic_bgp:
        config:
        state: delete
    
    - name: "Test vxlans deleted state 02"
      dellemc.enterprise_sonic.sonic_vxlans:
        config:
        state: deleted

    - name: Push Configurations For Custom CLIs
      vars:
        ansible_connection: network_cli
      sonic_config:
        src: fdc_clis.j2
      register: result
